### ISSUE TITLE
Why not add more properties to error objects?

### ISSUE THREAD

**Issue by dumbmatter** [dfahlander/typeson-registry#10]
In https://github.com/dfahlander/typeson-registry/blob/master/types/error.js and https://github.com/dfahlander/typeson-registry/blob/master/types/errors.js you restore the "name" and "message" properties of errors.

But [there are more nonstandard properties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error), most importantly [Error.stack](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack) which is just a string and although non-standard is widely supported. Firefox also has columnNumber, fileName, and lineNumber.

Is there any reason not to support all of those non-standard properties, if they are present?

**Comment by brettz9** [comment]
@dfahlander : Since this is not part of the Structured Cloning Algorithm or such which doesn't allow errors, it shouldn't hurt to add other such properties, no?

**Comment by dfahlander** [comment]
Sure, could definitely support them in case they are present. I think a PR of this would be easily done. I wouldn't have the time to PR it now, but I am definitely pro that change. 

A PR would go primarilary into [error.js](https://github.com/dfahlander/typeson-registry/blob/master/types/error.js#L5-L11). Firstly, in replace(), add the other prop names beside {name, message}, then in revive(), set the props in case they're not undefined.

Could also be accomplished with similar change in [errors.js](https://github.com/dfahlander/typeson-registry/blob/master/types/errors.js)

**Comment by brettz9** [comment]
I've updated my PR.

Btw and FWIW, I came across some additional info--it appears that `Error` may now become cloneable by the Structured Cloning Algorithm after all:

- https://github.com/mozilla/standards-positions/issues/165
- https://github.com/web-platform-tests/wpt/blob/master/IndexedDB/structured-clone.any.js#L192-L211 (Note that the tests it runs are for passing tests, unlike the "Non-serializable" type tests at the bottom)

I'm guessing that if the tests are already checking for it (and Chrome is already passing, though Firefox is not), we may want to support now?
