### ISSUE TITLE
File is changed on encapsulate

### ISSUE THREAD

**Issue by RatedDS** [dfahlander/typeson-registry#11]
I'm trying to encapsulate an image file to serialize it with BSON and send it over a Websocket, I managed to do it but nothing was rendered, so I did some tests and it seems that the File object has a different size and is changed after encapsulate and so isn't a valid image anymore.

![image](https://user-images.githubusercontent.com/14005823/39962617-ccd72ff6-5654-11e8-9904-671603d50255.png)

**Comment by brettz9** [comment]
This may have been fixed in the latest release...

**Comment by RatedDS** [comment]
I can confirm it's fixed.
