### ISSUE TITLE
FileList polyfill known issue

### ISSUE THREAD

**Issue by septs** [dfahlander/typeson-registry#21]
https://github.com/dfahlander/typeson-registry/blob/ee6234e78b672c50a5764f929e4ef8e6466b3c41/types/filelist.js#L16-L43

1. Cannot implement `[[index]]` internal slot
e.q: `filelist[0] === filelist.item(0)`
2. Not implement iterator
e.q: `Array.from(filelist)`

see https://www.w3.org/TR/FileAPI/#filelist-section

solution: use https://npm.im/create-file-list package

**Comment by septs** [comment]
@brettz9

**Comment by septs** [comment]
@brettz9

**Comment by brettz9** [comment]
Sounds good if it can pass our tests. From [source](https://github.com/fisker/create-file-list/blob/master/src/index.js), however, it looks like we would need other Node polyfills, or we could only use it for the browser.

**Comment by septs** [comment]
I think `Blob`, `File` and `FileList` is browser specific feature.

**Comment by brettz9** [comment]
They can work in Node with jsdom. See our tests.

**Comment by septs** [comment]
headless browser is not it a better choice?

**Comment by brettz9** [comment]
See https://github.com/dfahlander/typeson-registry/pull/18#issuecomment-671004853

**Comment by brettz9** [comment]
Btw, if you meant to suggest headless testing was better than normal Node tests, I think it is good that we have a special environment to show how it can work in regular Node.

Also, this looked like a fine item to add. Just need to see if we can get Node polyfills.  Looks like the `DataTransfer` API (and the clipboard API) was requested in https://github.com/jsdom/jsdom/issues/1568 where `create-file-list` just relies on one of these.
